name: Deploy

on:
  push:
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: liberica
        java-version: '11'
    - name: Update version
      run: |
        sed -i "s/VERSION_NAME=[0-9]*.[0-9]*.[0-9]*/VERSION_NAME=${GITHUB_REF#refs/tags/}/g" ./gradle.properties
        rm -rf gradle.propreties-e
        git config user.name "github-actions"
        git config user.email "tick.taku.77@gmail.com"
        git add .
        git commit -m "Update version ${GITHUB_REF#refs/tags/}"
